server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
  #   name: user-service
  # redis:
  #   host: localhost
  #   port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
token:
  expiration_time: 86400000
  secret: user_token
