server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
     name: user-service
  redis:
     host: localhost
     port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
token:
  expiration_time: 86400000
  secret: user_token

# AWS Account Credentials (AWS 접근 키)
cloud:
  aws:
    credentials:
      accessKey: AKIAXJUDK5ZD2WPT2PXC
      secretKey: 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
    # AWS S3 bucket Info (S3 버킷정보)
    s3.bucket: likelionvideo
    region:
      static: ap-northeast-2
    stack:
      auto: false


refer:
  host: http://localhost:3000/
