# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: flowbit-test-ci

on: # 이벤트 감지, 워크플로우를 실행시키는 조건 설정
  push:
    branches: [ develop ] # push 되면 실행될 브랜치 선택(main)
  pull_request:
    branches: [ develop ] # pull_request(PR) 되면 실행될 브랜치 선택(main)

jobs: # job - 하나의 인스턴스에서 여러 Step을 그룹시켜 실행하는 역할, 병렬로 실행
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: ✨ JDK 11 설정
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
  
    - name: ✨ Maven 의존성 캐싱
      uses: actions/cache@v3
      with:
        path: |
            ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
        restore-keys: |
            ${{ runner.os }}-maven-
            
    - name: ✨ maven 권한 설정
      run: chmod +x ./mvnw
      working-directory: ${{ env.working-directory }}
  
    - name: ✨ 테스트 진행
      run: mvn test
  
    - name: ✨ 테스트 결과 Report
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: ${{ always() }}
      with:
        files: '**/target/surefire-reports/TEST-*.xml'
  
    - name: ✨ 테스트 실패 Comment
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
  
